import LocalizedArticlePage from '@/components/LocalizedArticlePage';
import { asLocale, buildLocalizedMetadata, SupportedLocale } from '@/lib/seo';

const copy = {
  zh: { title: '使用条款', sections: [['信息性质', '本站提供旅行信息、票券筛选与估算工具，不是铁路运营公司、旅行社或实时订票系统。计算结果不构成价格保证、法律建议或运输合同。'], ['本站不销售周游券', '本站不发行、持有或直接销售铁路周游券，也不向用户收取票款。点击购买或查看价格按钮后，您会进入运营方或合作平台的网站。'], ['第三方交易', '票券销售合同、扣款、收据、交付、改签、取消、退款与客户支持均由实际销售者处理，并适用其条款与隐私政策。本站不代表实际销售者承诺库存、售价、资格或退款。'], ['Affiliate 关系', '明确标注的合作链接可能让本站在购买成立时获得佣金，通常不会提高用户支付价格。佣金不会改变计算规则、信息核验或推荐结论。'], ['官方条件优先', '票价、适用资格、覆盖范围、退款、指定席和运行状态可能变化。购买与乘车前必须在运营方或实际销售平台确认；与本站内容不一致时，以其最新条款为准。'], ['知识产权', '本站原创文字、界面与工具受适用法律保护。铁路公司名称和商标属于其权利人；引用不表示获得官方背书。'], ['责任限制', '在法律允许范围内，本站不对班次取消、信息变更、误车、额外票价或第三方服务造成的间接损失负责。']], updated: '最后更新：2026-09-10' },
  en: { title: 'Terms of Use', sections: [['Nature of the information', 'This site provides travel information, pass filtering and estimation tools. It is not a rail operator, travel agency or real-time booking system. Results are not a price guarantee, legal advice or a transport contract.'], ['We do not sell rail passes', 'This site does not issue, hold or directly sell rail passes and does not collect rail fares. Purchase and price buttons take you to an operator or partner platform.'], ['Third-party transactions', 'The actual seller handles the sales contract, charge, receipt, delivery, changes, cancellation, refund and customer support under its own terms and privacy policy. We do not promise inventory, price, eligibility or refunds on its behalf.'], ['Affiliate relationship', 'Clearly marked partner links may pay this site a commission when a purchase is completed, normally without increasing the user’s price. Commission does not change calculator rules, source verification or editorial conclusions.'], ['Official conditions take priority', 'Fares, eligibility, coverage, refunds, reserved seats and operating status can change. Confirm them with the operator or actual seller before purchase and travel. Their latest terms prevail if they differ from this site.'], ['Intellectual property', 'Original text, interfaces and tools on this site are protected by applicable law. Railway names and marks belong to their owners; reference to them does not imply endorsement.'], ['Limitation of liability', 'To the extent permitted by law, the site is not responsible for indirect loss caused by cancellations, information changes, missed trains, additional fares or third-party services.']], updated: 'Last updated: 2026-09-10' },
  ja: { title: '利用規約', sections: [['情報の性質', '当サイトは旅行情報、きっぷの絞り込み、試算ツールを提供します。鉄道事業者、旅行会社、リアルタイム予約システムではありません。結果は価格保証、法的助言、運送契約を構成しません。'], ['鉄道パスを販売しません', '当サイトは鉄道パスを発行、保有、直接販売せず、代金を受領しません。購入・価格確認ボタンから運行会社または提携販売サイトへ移動します。'], ['第三者との取引', '売買契約、決済、領収書、引渡し、変更、取消、払戻し、顧客対応は、実際の販売者がその規約・プライバシーポリシーに基づき行います。当サイトが販売者に代わって在庫、価格、資格、払戻しを保証しません。'], ['アフィリエイト関係', '明示した提携リンク経由で購入が成立すると、通常お客様の支払額を増やすことなく当サイトが報酬を受け取る場合があります。報酬は計算規則、情報確認、編集上の結論に影響しません。'], ['公式条件の優先', '運賃、利用資格、利用範囲、払い戻し、指定席、運行状況は変更される場合があります。購入・乗車前に運行会社または実際の販売者で確認し、当サイトと異なる場合はその最新条件を優先してください。'], ['知的財産', '当サイト独自の文章、画面、ツールは適用法令で保護されます。鉄道会社の名称・商標は各権利者に帰属し、記載は公式な推奨を意味しません。'], ['責任の制限', '法令で認められる範囲において、運休、情報変更、乗り遅れ、追加運賃、第三者サービスによる間接損害について責任を負いません。']], updated: '最終更新：2026-09-10' },
} satisfies Record<SupportedLocale, { title: string; sections: string[][]; updated: string }>;

export async function generateMetadata({ params }: { params: Promise<{ lang: string }> }) { const { lang } = await params; return buildLocalizedMetadata({ lang, path: 'terms', titles: { zh: '使用条款｜FindMyJR-Pass', en: 'Terms of Use | FindMyJR-Pass', ja: '利用規約｜FindMyJR-Pass' }, descriptions: { zh: '使用 FindMyJR-Pass 的信息、估算工具和第三方购票链接时适用的条款。', en: 'Terms governing the information, estimation tools and third-party purchase links on FindMyJR-Pass.', ja: 'FindMyJR-Passの情報、試算ツール、第三者の購入リンクに適用される利用規約です。' } }); }

export default async function TermsPage({ params }: { params: Promise<{ lang: string }> }) { const { lang } = await params; const locale = asLocale(lang); const t = copy[locale]; return <LocalizedArticlePage lang={locale} title={t.title}>{t.sections.map(([heading, body]) => <section key={heading}><h2>{heading}</h2><p>{body}</p></section>)}<p className="text-sm text-slate-500">{t.updated}</p></LocalizedArticlePage>; }
