import LocalizedArticlePage from '@/components/LocalizedArticlePage';
import { asLocale, buildLocalizedMetadata, SupportedLocale } from '@/lib/seo';

const copy = {
  zh: { title: '隐私与 Cookie 政策', intro: '本站遵循数据最小化原则。浏览静态页面无需注册，本站也不直接保存护照、银行卡或旅行证件资料。', analyticsTitle: '访问分析', analytics: '只有在您同意可选 Cookie 后，已正确配置的 Google Analytics 才会加载。它可能处理页面访问、设备类型、来源页面、国家或地区级位置和站内操作，用于改善内容；本站不会故意把姓名、邮箱、银行卡信息或完整行程发送到分析事件。', adsTitle: '广告与同意管理', ads: 'Google AdSense 默认关闭。只有在发布商账号、广告位和 Google 认证的同意管理平台均已正确配置，且您允许可选用途后，广告组件才可加载。Google 及广告合作方会依其政策处理 Cookie、设备与广告衡量数据。', choiceTitle: '保存与撤回选择', choice: '您的选择保存在浏览器本地存储 findmyrailpass-consent-v1 中，不会上传到本站服务器。可随时点击页面左下角的“Cookie 设置”改变选择；从允许改为拒绝时页面会重新加载并停止再次载入可选脚本。', affiliateTitle: 'Affiliate 跳转与付款资料', affiliate: '点击合作链接会离开本站。票券浏览、订单、付款、发票、取消与退款资料由实际销售者按其隐私政策处理。本站不接收银行卡号、护照资料或完整付款信息，但可能收到不含这些资料的订单归因或佣金报告。', contactTitle: '联系与删除请求', contact: '通过邮件联系时，我们仅使用您主动提供的信息回复问题。', request: '隐私请求', noEmail: '联系邮箱尚未公开；请先不要通过本站发送个人或付款资料。', updated: '最后更新：2026-09-10' },
  en: { title: 'Privacy and Cookie Policy', intro: 'This site follows data-minimisation principles. Static pages require no registration, and we do not directly store passport, payment-card or travel-document details.', analyticsTitle: 'Analytics', analytics: 'A correctly configured Google Analytics property loads only after you allow optional cookies. It may process page visits, device type, referrer, country- or region-level location and on-site actions to improve content. We do not intentionally send names, email addresses, payment-card data or complete itineraries in analytics events.', adsTitle: 'Advertising and consent management', ads: 'Google AdSense is off by default. Ad components can load only after the publisher account, ad slots and a Google-certified consent management platform are configured and you allow optional purposes. Google and advertising partners then process cookies, device and ad-measurement data under their policies.', choiceTitle: 'Saving and withdrawing your choice', choice: 'Your choice is stored in your browser as findmyrailpass-consent-v1 and is not uploaded to our server. Use “Cookie settings” at the lower left to change it. Moving from allow to necessary-only reloads the page and prevents optional scripts from loading again.', affiliateTitle: 'Affiliate referrals and payment data', affiliate: 'Partner links take you away from this site. The actual seller processes browsing, orders, payment, invoices, cancellations and refunds under its privacy policy. We do not receive payment-card numbers, passport data or full payment details, but may receive attribution or commission reports without those details.', contactTitle: 'Contact and deletion requests', contact: 'When you contact us by email, we use information you voluntarily provide only to answer your request.', request: 'Privacy requests', noEmail: 'No public contact email is configured yet; do not send personal or payment data through this site.', updated: 'Last updated: 2026-09-10' },
  ja: { title: 'プライバシー・Cookieポリシー', intro: '当サイトはデータ最小化の原則に従います。静的ページの閲覧に登録は不要で、パスポート、決済カード、旅行書類の情報を直接保存しません。', analyticsTitle: 'アクセス解析', analytics: '適切に設定されたGoogle Analyticsは、任意Cookieを許可した場合にのみ読み込みます。内容改善のため、ページ閲覧、端末種別、参照元、国・地域レベルの位置、サイト内操作を処理することがあります。氏名、メールアドレス、カード情報、完全な旅程を意図的に解析イベントへ送信しません。', adsTitle: '広告・同意管理', ads: 'Google AdSenseは初期状態で無効です。パブリッシャーアカウント、広告枠、Google認定の同意管理プラットフォームを設定し、お客様が任意目的を許可した場合に限り広告機能を読み込めます。その場合、Googleおよび広告パートナーは各社方針に基づきCookie、端末、広告測定データを処理します。', choiceTitle: '選択の保存・撤回', choice: '選択はブラウザのローカルストレージ findmyrailpass-consent-v1 に保存し、当サイトのサーバーへ送信しません。左下の「Cookie設定」から変更できます。許可から必須機能のみに変更するとページを再読み込みし、任意スクリプトの再読込みを停止します。', affiliateTitle: 'アフィリエイト送客・決済情報', affiliate: '提携リンクをクリックすると当サイトを離れます。閲覧、注文、決済、領収書、取消、払戻しの情報は実際の販売者がそのプライバシーポリシーに基づき処理します。当サイトはカード番号、パスポート情報、完全な決済情報を受け取りませんが、それらを含まない成果計測・報酬レポートを受け取る場合があります。', contactTitle: 'お問い合わせ・削除依頼', contact: 'メールでお問い合わせいただいた場合、任意に提供された情報を回答のためだけに使用します。', request: 'プライバシーに関する連絡先', noEmail: '公開連絡先は未設定です。当サイトを通じて個人情報・決済情報を送信しないでください。', updated: '最終更新：2026-09-10' },
} satisfies Record<SupportedLocale, Record<string, string>>;

export async function generateMetadata({ params }: { params: Promise<{ lang: string }> }) { const { lang } = await params; return buildLocalizedMetadata({ lang, path: 'privacy', titles: { zh: '隐私与 Cookie 政策｜FindMyJR-Pass', en: 'Privacy and Cookie Policy | FindMyJR-Pass', ja: 'プライバシー・Cookieポリシー｜FindMyJR-Pass' }, descriptions: { zh: '了解本站如何处理同意设置、访问分析、广告 Cookie、Affiliate 跳转和联系信息。', en: 'How this site handles consent settings, analytics, advertising cookies, affiliate referrals and contact information.', ja: '同意設定、アクセス解析、広告Cookie、アフィリエイト送客、お問い合わせ情報の取扱いを説明します。' } }); }

export default async function PrivacyPage({ params }: { params: Promise<{ lang: string }> }) { const { lang } = await params; const locale = asLocale(lang); const t = copy[locale]; const email = process.env.NEXT_PUBLIC_CONTACT_EMAIL; return <LocalizedArticlePage lang={locale} title={t.title}><p>{t.intro}</p><h2>{t.analyticsTitle}</h2><p>{t.analytics}</p><h2>{t.adsTitle}</h2><p>{t.ads}</p><h2>{t.choiceTitle}</h2><p>{t.choice}</p><h2>{t.affiliateTitle}</h2><p>{t.affiliate}</p><h2>{t.contactTitle}</h2><p>{t.contact} {email ? <>{t.request}: <a className="font-bold text-primary" href={`mailto:${email}`}>{email}</a>.</> : t.noEmail}</p><p className="text-sm text-slate-500">{t.updated}</p></LocalizedArticlePage>; }
