// Generated by scripts/check-directory-links.mjs.
export const DIRECTORY_LINKS_CHECKED_AT = "2026-09-03T05:56:26.019Z";
export const UNREACHABLE_DIRECTORY_URLS = [
  "http://www.naga-den.com/publics/index/11/",
  "https://www.jr-eki.com/ticket/brand/2-5IM",
  "https://www.solaseedair.jp/promotion/jrkyushu-freeticket/",
  "https://www.tokyodisneyresort.jp/tdr/resortline/fare/"
] as const;
